version: '3.7'

services:
  redis:
    image: redis:6
    container_name: mayan-redis

  mayan-postgres:
    image: postgres:13
    container_name: mayan-postgres
    restart: always
    volumes:
      - mayan-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mayan
      POSTGRES_USER: mayan
      POSTGRES_PASSWORD: mayanpassword

  mayan-edms:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mayan-edms
    ports:
      - "8000:8000"
    volumes:
      - mayan-edms-data:/var/lib/mayan
      - mayan-cache:/var/cache/mayan
      - mayan-whoosh:/var/lib/mayan/whoosh
    depends_on:
      - mayan-postgres
      - redis
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: mayan-postgres
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayanpassword
      MAYAN_DATABASE_USER: mayan
      MAYAN_CELERY_BROKER_URL: redis://redis:6379/0

  worker:
    image: mayanedms/mayanedms:latest
    container_name: mayan-worker
    command: run_worker
    depends_on:
      - mayan-edms
      - mayan-postgres
      - redis
    volumes:
      - mayan-edms-data:/var/lib/mayan
      - mayan-cache:/var/cache/mayan
      - mayan-whoosh:/var/lib/mayan/whoosh
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_PASSWORD: mayanpassword
      MAYAN_DATABASE_HOST: mayan-postgres
      MAYAN_CELERY_BROKER_URL: redis://redis:6379/0
      MAYAN_QUEUE_LIST: default,converter,documents,indexing,mailing,metadata,ocr,parsing,search,signatures,statistics,storage,task_manager,views

volumes:
  mayan-edms-data:
  mayan-postgres-data:
  mayan-cache:
  mayan-whoosh:
